---
- name: Converge
  hosts: all
  roles:
    - role: wouterdt.firefox
  vars:
    firefox_profile:
      - username: user1
        profile: default
        config:
          general.useragent.override: "Mozilla 5"
      - username: user2
        profile: test
